version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install boto3 --quiet

  pre_build:
    commands:
      - echo "Validando archivos"
      - test -f procesar.py || exit 1
      - test -f datos.txt   || exit 1
      - echo "Archivos validados"

  build:
    commands:
      - echo "Ejecutando procesador"
      - python procesar.py

  post_build:
    commands:
      - echo "Subiendo log a S3"
      - aws s3 cp backup.log s3://$BUCKET_NAME/backup.log
      - echo "Completado"

artifacts:
  files:
    - backup.log